version: 2.1

jobs:
  build:
    docker:
      - image: node:16
    working_directory: ~/awesome-use-hooks
    steps:
      - checkout
      - run:
          name: 'Installing Dependencies'
          command: yarn install
      - run:
          name: 'Build Production'
          command: yarn build
  # test:
  #   docker:
  #     - image: node:16
  #   working_directory: ~/awesome-use-hooks
  #   steps:
  #     - checkout
  #     - run:
  #         name: 'Installing Dependencies'
  #         command: yarn install
  #     - run:
  #         name: 'Run Unit Tests'
  #         command: yarn test

workflows:
  version: 2
  build_test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
